version: '3'

services:
   db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
    environment:
       - 'MYSQL_ROOT_PASSWORD=1234'
    networks: 
      - backend

   recipe-app:
     build: ./compose/mysql/
     depends_on:
        - db
     ports:
        - 8090:8080
     environment:
        - 'DB_PORT=3306'
        - 'DB_HOST=db'
        - 'DB_NAME=recipe-app-db'
        - 'DB_USERNAME=dev'
        - 'DB_PASSWORD=1234'
      networks: 
      - backend
      
   tomcat: 
    image: tomcat:9-jre8
    container_name: tomcat
    ports:
      - 8070:8080
      - 443:443
    networks:
      - backend
    links:
      - recipe-app

networks:
  backend:
    driver: "bridge"
